version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    assignees:
      - hywznn
    labels:
      - dependencies
      - security:update
      - area:front
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0
    assignees:
      - hywznn
    labels:
      - dependencies
      - security:update
      - area:ci
